language: php

php:
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install
  # - cd public
  # - sudo apt-get install -y nodejs
  # - sudo apt-get install -y build-essential
  # - sudo npm install && bower install
  # - grunt test

script:
    - vendor/bin/phpunit
