language: php

php:
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
    # - vendor/bin/phpunit

notifications:
  slack: angularjsrecipes:aIYCzMyreDRBXh0BMoaF1czk
